name: Atualizar Ranking

on:
  schedule:
    - cron: "*/10 * * * *"  # roda a cada 10 minutos
  workflow_dispatch:        # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pillow requests

      - name: Executar script
        run: python screenshot.py

      - name: Commit e Push das mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ranking.png embed.html
          git commit -m "🔄 Atualizando ranking automático"
          git push
