name: Update Ranking

on:
  schedule:
    - cron: "*/2 * * * *" # a cada 30 minutos
  workflow_dispatch: # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pillow requests

      - name: Run script
        run: python screenshot.py

      - name: Commit updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ranking.png embed.html
          git commit -m "Update ranking image and embed" || echo "No changes to commit"
          git push
