name: Atualizar Ranking GTA

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # roda a cada 6h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script e gerar imagem
        run: python screenshot.py

      - name: Commit e push do ranking
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ranking.png
          git commit -m "🔄 Atualizar ranking automático" || echo "Sem alterações"
          git push
