name: Update Ranking

on:
  schedule:
    - cron: "*/2 * * * *"   # tenta a cada 2 min
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pillow requests

      - name: Run screenshot.py (gera ranking.png e embed.html)
        run: python screenshot.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/ranking.png docs/embed.html
          git commit -m "Atualiza ranking automático" || echo "Nenhuma mudança"
          git push

      - name: Check if GitHub Pages synced
        run: python check_pages.py
