name: Update Ranking

on:
  schedule:
    - cron: "0 * * * *"   # roda de hora em hora
  workflow_dispatch:       # permite rodar manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run screenshot
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python screenshot.py

      - name: Commit and push updated image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/ranking.png || true
          git commit -m "Update ranking image" || echo "No changes to commit"
          git push
